version: "2.3"

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=sqlite:////var/sqlitedb/ctfd.db
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=false
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .data/sqlitedb:/var/sqlitedb/
      - .data/filesystem_cache:/var/cache/CTFd
      - .:/opt/CTFd:ro
    networks:
        default:
        internal:

networks:
    default:
    internal:
        internal: true
